[target.x86_64-pc-windows-msvc]
linker = "C:/Users/Administrator/.rustup/toolchains/stable-x86_64-pc-windows-msvc/lib/rustlib/x86_64-pc-windows-msvc/bin/rust-lld.exe"
rustflags = [
  "-L", "native=C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/crt/lib/x86_64",
  "-L", "native=C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/sdk/lib/um/x86_64",
  "-L", "native=C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/sdk/lib/ucrt/x86_64",
        ]

[env]
LIB = { value = "C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/crt/lib/x86_64;C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/sdk/lib/um/x86_64;C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/sdk/lib/ucrt/x86_64" }
INCLUDE = { value = "C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/crt/include;C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/sdk/include/ucrt;C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/sdk/include/um;C:/Users/Administrator/AppData/Local/Temp/opencode/xwin/sdk/sdk/include/shared" }